### PR TITLE
Add image aspect ratio in the title

### PR DESCRIPTION
**Pull request by darkred**
Greetings @tophf 

I'd like to make an addition to my old PR #2 ('image megapixel value in the title'):
i.e. to add image [aspect ratio](https://en.wikipedia.org/wiki/Aspect_ratio_(image)#Still_photography) in the title, e.g. `1:1`, `5:4`, `4:3`, `16:9`, etc.

The function in the PR is mostly taken from [this StackOverflow answer](https://stackoverflow.com/a/43016456/3231411).
It's the best rational approximation algorithm with adjustable level of fuzziness (I used `20`).

Screenshot:

For reference here is an example screenshot of IrfanView  | Image Properties, which provides such info:

I hope you like my suggestion.

### CODE REVIEW

**Comment by tophf** [comment]
That's a lot of code. Try something smaller e.g. https://stackoverflow.com/questions/4652468/

**Comment by darkred** [comment]
I tried simpler approaches before I submitted this PR, like this one:

```js
function aspectRatio(numerator, denominator) {
  var gcd = function gcd(a, b) {
    return b ? gcd(b, a % b) : a;
  };
  gcd = gcd(numerator, denominator);
  return numerator / gcd < 20 &&
    denominator / gcd < 20
    ? `${numerator / gcd}:${denominator / gcd}`
    : (numerator / denominator).toFixed(2);
}
```

but it displays decimals more times than fractions:

*while the initial approach would **always** display fractions, approximations when needed*.

Do you prefer this one?

---

For reference IrfanView indeed displays decimals in many cases, e.g.
1507x2048 --> `0.73`
2048x969  --> `2.11`
but it also shows approximated fractions in many cases, e.g.
640x1136  --> `9:16` while this approach would show 0.56, rounded from 0.5633802...etc
4505x3003 --> `3:2` while this approach would shows 1.50, rounded from 1.500166...etc

**Comment by tophf** [comment]
Interesting... I guess we should use Fibonacci approximation.
Try this code and see if its thresholds (20, 1e-3, 1e-13) need an adjustment.
```js
function aspectRatio(w, h) {
  for (let err, rat = w / h, a, b = 0; ;) {
    b++;
    a = Math.round((w * b) / h);
    if (a > 20 || b > 20)
      return (w / h).toFixed(2);
    err = Math.abs(a / b - rat);
    if (err < 1e-3)
      return `${err < 1e-13 ? '' : '~'}${a}:${b}`;
  }
}
```

**Comment by darkred** [comment]
I love your approach! So elegant! It would definitely deserve all the votes in StackOverflow!
Thanks a lot!

Just one suggestion: the lowest values of `err` that I encountered were values of 0.00001 and over,
so, instead of changing `1e-13` to `1e-5` 
I'd say to drop using the `~` (approximation) symbol altogether, just as IrfanView doesn't make such distinction.
So, I'd say to make the last part as:

```js
if (err < 1e-3)
  return `${a}:${b}`;
```

That's what I just committed.
If you prefer to keep the tilde, please post the threshold you like, and I'd gladly change it.

**Comment by tophf** [comment]
I've browsed an image site for a while and simplified the thresholds even further.

**Comment by darkred** [comment]
It's perfect! Thank you.

**Review by tophf — APPROVED** [review]

**Pull request merged**
