### PR TITLE
Fix instagram rule incorrectly matching the space between images

### PR DESCRIPTION
**Pull request by Ryujinra**
Each row of images is contained in a div element matched by the old rule, so that hovering in the whitespace between images would incorrectly cause mpiv to load the first image, when it should do nothing.

### CODE REVIEW

**Comment by tophf** [comment]
It breaks matching of the post view like this:



Also when it's opened in a tab.

**Comment by tophf** [comment]
I'll fix it myself as there is also a regression with choosing the best size inside the post view.

**Comment by Ryujinra** [comment]
I think we can just match divs with `_` (underscore) in class, but I didn't test thoroughly.

**Comment by tophf** [comment]
Their class names are random so they change periodically and unpredictably, the underscore may be just a random character.

**Comment by Ryujinra** [comment]
I guess just matching the  element with srcset attribute `instagram.*fbcdn.net`?

**Comment by tophf** [comment]
They have a `div` element that's covering the image. I could hide it temporarily during matching via the rule's `css` property but I don't like doing this as it causes a lot of internal calculations in the browser to update the CSSOM.

**Comment by tophf** [comment]
So I ended up simplifying the selectors. Seems to work in my tests.

**Comment by Ryujinra** [comment]
Seems to work for me. I also tested with `'div[class*=_]'` added to the old rule which seemed to work for me, but since the class naming convention is more likely to change in the future, your way is probably better.

**Comment by Ryujinra** [comment]
Actually, your new rule triggers when mouse is over the comment section because that element has the `role="button"` attribute as well. Will probably have to use the `tabindex` attribute as well to further limit it, or use `'div[class*=_]'` like above.

**Pull request closed without merging**
